### ISSUE TITLE
Ios orientation issue

### ISSUE THREAD

**Issue by Nic01as** [medooze/video-codecs-node#2]
Hello ! Thanks for your amazing work !

When I transcode a Stream coming from an iPhone with VideoEncoder, the image of the output is always displayed in the landscape mode and not rotated like the source is.
I have the impression that we lose the data of the orientation.
When I make the same test with android, when the source switches from landscape to portrait, it is working every time.

Do you have any idea on how to fix this?

Example: 
![image](https://user-images.githubusercontent.com/26201907/108880217-5ac7fc80-7602-11eb-9a81-f1854aa4e452.png)
Thanks!

**Comment by murillo128** [comment]
Check if you have enabled the 3gpp-video-orientation extension header. Currently the video-codecs does not take that information into account so image will not be rotated.

If the header extension is not negotiated/supported, the sender has to rotate the image before encoding and the transcoding will work correctly.

**Comment by Nic01as** [comment]
I removed the extension and now it works, thanks!
